#pragma warning disable CS0168, CS0219
/* Generated By:CSharpCC: Do not edit this line. SequenceParserTokenManager.cs */
namespace de.unika.ipd.grGen.libGr.sequenceParser {

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using de.unika.ipd.grGen.libGr;

public class SequenceParserTokenManager : SequenceParserConstants {
  public  System.IO.TextWriter debugStream = Console.Out;
  public  void SetDebugStream(System.IO.TextWriter ds) { debugStream = ds; }
private int mccStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 8796093022208L) != 0L)
            return 60;
         if ((active0 & -281474976710656L) != 0L || (active1 & 1L) != 0L)
         {
            mccmatchedKind = 78;
            return 11;
         }
         return -1;
      case 1:
         if ((active0 & 54043195528445952L) != 0L)
            return 11;
         if ((active0 & -54324670505156608L) != 0L || (active1 & 1L) != 0L)
         {
            if (mccmatchedPos != 1) {
               mccmatchedKind = 78;
               mccmatchedPos = 1;
            }
            return 11;
         }
         return -1;
      case 2:
         if ((active0 & 11540474045136896L) != 0L)
            return 11;
         if ((active0 & -65865144550293504L) != 0L || (active1 & 1L) != 0L)
         {
            mccmatchedKind = 78;
            mccmatchedPos = 2;
            return 11;
         }
         return -1;
      case 3:
         if ((active0 & -2953235455648202752L) != 0L)
         {
            mccmatchedKind = 78;
            mccmatchedPos = 3;
            return 11;
         }
         if ((active0 & 2887370311097909248L) != 0L || (active1 & 1L) != 0L)
            return 11;
         return -1;
      case 4:
         if ((active0 & -4539628424389459968L) != 0L)
         {
            mccmatchedKind = 78;
            mccmatchedPos = 4;
            return 11;
         }
         if ((active0 & 1586392968741257216L) != 0L)
            return 11;
         return -1;
      case 5:
         if ((active0 & -4539628424389459968L) != 0L)
         {
            mccmatchedKind = 78;
            mccmatchedPos = 5;
            return 11;
         }
         return -1;
      case 6:
         if ((active0 & -9223372036854775808L) != 0L)
         {
            mccmatchedKind = 78;
            mccmatchedPos = 6;
            return 11;
         }
         if ((active0 & 4683743612465315840L) != 0L)
            return 11;
         return -1;
      default :
         return -1;
   }
}
private int mccStartNfa_0(int pos, long active0, long active1)
{
   return mccMoveNfa_0(mccStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int mccStopAtPos(int pos, int kind)
{
   mccmatchedKind = kind;
   mccmatchedPos = pos;
   return pos + 1;
}
private int mccStartNfaWithStates_0(int pos, int kind, int state) {
   mccmatchedKind = kind;
   mccmatchedPos = pos;
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) { return pos + 1; }
   return mccMoveNfa_0(state, pos + 1);
}
private int mccMoveStringLiteralDfa0_0()
{
   switch((int)curChar) {
      case 33:
         mccmatchedKind = 26;
         return mccMoveStringLiteralDfa1_0(131072L, 0L);
      case 36:
         return mccStopAtPos(0, 10);
      case 37:
         return mccStopAtPos(0, 39);
      case 38:
         mccmatchedKind = 12;
         return mccMoveStringLiteralDfa1_0(2304L, 0L);
      case 40:
         return mccStopAtPos(0, 27);
      case 41:
         return mccStopAtPos(0, 28);
      case 42:
         return mccStopAtPos(0, 22);
      case 43:
         return mccStopAtPos(0, 23);
      case 44:
         return mccStopAtPos(0, 9);
      case 45:
         mccmatchedKind = 80;
         return mccMoveStringLiteralDfa1_0(4398046511104L, 0L);
      case 46:
         return mccStartNfaWithStates_0(0, 43, 60);
      case 47:
         return mccStopAtPos(0, 24);
      case 58:
         mccmatchedKind = 37;
         return mccMoveStringLiteralDfa1_0(274877906944L, 0L);
      case 59:
         mccmatchedKind = 46;
         return mccMoveStringLiteralDfa1_0(175921860444160L, 0L);
      case 60:
         mccmatchedKind = 31;
         return mccMoveStringLiteralDfa1_0(17600776241152L, 0L);
      case 61:
         mccmatchedKind = 5;
         return mccMoveStringLiteralDfa1_0(65600L, 0L);
      case 62:
         mccmatchedKind = 32;
         return mccMoveStringLiteralDfa1_0(17180393472L, 32768L);
      case 63:
         return mccStopAtPos(0, 40);
      case 64:
         return mccStopAtPos(0, 41);
      case 91:
         return mccStopAtPos(0, 29);
      case 92:
         return mccStopAtPos(0, 25);
      case 93:
         return mccStopAtPos(0, 30);
      case 94:
         return mccStopAtPos(0, 15);
      case 99:
         return mccMoveStringLiteralDfa1_0(1441151880758558720L, 0L);
      case 100:
         return mccMoveStringLiteralDfa1_0(281474976710656L, 0L);
      case 102:
         return mccMoveStringLiteralDfa1_0(10133099161583616L, 0L);
      case 105:
         return mccMoveStringLiteralDfa1_0(54043195528445952L, 0L);
      case 108:
         return mccMoveStringLiteralDfa1_0(0L, 1L);
      case 110:
         return mccMoveStringLiteralDfa1_0(6755399441055744L, 0L);
      case 112:
         return mccMoveStringLiteralDfa1_0(-9223372036854775808L, 0L);
      case 115:
         return mccMoveStringLiteralDfa1_0(2305843009213693952L, 0L);
      case 116:
         return mccMoveStringLiteralDfa1_0(5188709720684232704L, 0L);
      case 118:
         return mccMoveStringLiteralDfa1_0(72057594037927936L, 0L);
      case 121:
         return mccMoveStringLiteralDfa1_0(144115188075855872L, 0L);
      case 123:
         return mccStopAtPos(0, 35);
      case 124:
         mccmatchedKind = 14;
         return mccMoveStringLiteralDfa1_0(8320L, 0L);
      case 125:
         return mccStopAtPos(0, 36);
      case 126:
         mccmatchedKind = 21;
         return mccMoveStringLiteralDfa1_0(1048576L, 0L);
      default :
         return mccMoveNfa_0(0, 0);
   }
}
private int mccMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch((int)curChar) {
      case 38:
         if ((active0 & 2048L) != 0L)
            return mccStopAtPos(1, 11);
         break;
      case 58:
         if ((active0 & 274877906944L) != 0L)
            return mccStopAtPos(1, 38);
         break;
      case 59:
         if ((active0 & 17592186044416L) != 0L)
            return mccStopAtPos(1, 44);
         else if ((active0 & 140737488355328L) != 0L)
            return mccStopAtPos(1, 47);
         break;
      case 60:
         if ((active0 & 8589934592L) != 0L)
            return mccStopAtPos(1, 33);
         break;
      case 61:
         if ((active0 & 65536L) != 0L)
            return mccStopAtPos(1, 16);
         else if ((active0 & 131072L) != 0L)
            return mccStopAtPos(1, 17);
         else if ((active0 & 262144L) != 0L)
            return mccStopAtPos(1, 18);
         else if ((active0 & 524288L) != 0L)
            return mccStopAtPos(1, 19);
         break;
      case 62:
         if ((active0 & 64L) != 0L)
            return mccStopAtPos(1, 6);
         else if ((active0 & 128L) != 0L)
            return mccStopAtPos(1, 7);
         else if ((active0 & 256L) != 0L)
            return mccStopAtPos(1, 8);
         else if ((active0 & 17179869184L) != 0L)
         {
            mccmatchedKind = 34;
            mccmatchedPos = 1;
         }
         else if ((active0 & 4398046511104L) != 0L)
            return mccStopAtPos(1, 42);
         else if ((active0 & 35184372088832L) != 0L)
            return mccStopAtPos(1, 45);
         return mccMoveStringLiteralDfa2_0(active0, 0L, active1, 32768L);
      case 97:
         return mccMoveStringLiteralDfa2_0(active0, -9222246136947933184L, active1, 0L);
      case 99:
         return mccMoveStringLiteralDfa2_0(active0, 2305843009213693952L, active1, 0L);
      case 101:
         return mccMoveStringLiteralDfa2_0(active0, 2533274790395904L, active1, 0L);
      case 102:
         if ((active0 & 18014398509481984L) != 0L)
            return mccStartNfaWithStates_0(1, 54, 11);
         break;
      case 104:
         return mccMoveStringLiteralDfa2_0(active0, 576460752303423488L, active1, 0L);
      case 105:
         return mccMoveStringLiteralDfa2_0(active0, 216172782113783808L, active1, 0L);
      case 108:
         return mccMoveStringLiteralDfa2_0(active0, 1152921504606846976L, active1, 0L);
      case 110:
         if ((active0 & 36028797018963968L) != 0L)
            return mccStartNfaWithStates_0(1, 55, 11);
         break;
      case 111:
         return mccMoveStringLiteralDfa2_0(active0, 297237575406452736L, active1, 1L);
      case 114:
         return mccMoveStringLiteralDfa2_0(active0, 4612248968380809216L, active1, 0L);
      case 117:
         return mccMoveStringLiteralDfa2_0(active0, 4503599627370496L, active1, 0L);
      case 124:
         if ((active0 & 8192L) != 0L)
            return mccStopAtPos(1, 13);
         break;
      case 126:
         if ((active0 & 1048576L) != 0L)
            return mccStopAtPos(1, 20);
         break;
      default :
         break;
   }
   return mccStartNfa_0(0, active0, active1);
}
private int mccMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return mccStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch((int)curChar) {
      case 62:
         if ((active1 & 32768L) != 0L)
            return mccStopAtPos(2, 79);
         break;
      case 97:
         return mccMoveStringLiteralDfa3_0(active0, 3458764513820540928L, active1, 0L);
      case 99:
         return mccMoveStringLiteralDfa3_0(active0, 0L, active1, 1L);
      case 101:
         return mccMoveStringLiteralDfa3_0(active0, 144115188075855872L, active1, 0L);
      case 102:
         if ((active0 & 281474976710656L) != 0L)
            return mccStartNfaWithStates_0(2, 48, 11);
         break;
      case 105:
         return mccMoveStringLiteralDfa3_0(active0, 576460752303423488L, active1, 0L);
      case 108:
         return mccMoveStringLiteralDfa3_0(active0, 5629499534213120L, active1, 0L);
      case 114:
         if ((active0 & 9007199254740992L) != 0L)
            return mccStartNfaWithStates_0(2, 53, 11);
         return mccMoveStringLiteralDfa3_0(active0, -9223372036854775808L, active1, 0L);
      case 115:
         return mccMoveStringLiteralDfa3_0(active0, 72057594037927936L, active1, 0L);
      case 117:
         return mccMoveStringLiteralDfa3_0(active0, 288793326105133056L, active1, 0L);
      case 119:
         if ((active0 & 2251799813685248L) != 0L)
            return mccStartNfaWithStates_0(2, 51, 11);
         break;
      case 121:
         return mccMoveStringLiteralDfa3_0(active0, 4611686018427387904L, active1, 0L);
      default :
         break;
   }
   return mccStartNfa_0(1, active0, active1);
}
private int mccMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return mccStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch((int)curChar) {
      case 97:
         return mccMoveStringLiteralDfa4_0(active0, -9223372036854775808L, active1, 0L);
      case 101:
         if ((active0 & 562949953421312L) != 0L)
            return mccStartNfaWithStates_0(3, 49, 11);
         break;
      case 105:
         return mccMoveStringLiteralDfa4_0(active0, 72057594037927936L, active1, 0L);
      case 107:
         if ((active1 & 1L) != 0L)
            return mccStartNfaWithStates_0(3, 64, 11);
         break;
      case 108:
         if ((active0 & 4503599627370496L) != 0L)
            return mccStartNfaWithStates_0(3, 52, 11);
         return mccMoveStringLiteralDfa4_0(active0, 144115188075855872L, active1, 0L);
      case 110:
         if ((active0 & 2305843009213693952L) != 0L)
            return mccStartNfaWithStates_0(3, 61, 11);
         return mccMoveStringLiteralDfa4_0(active0, 288230376151711744L, active1, 0L);
      case 115:
         if ((active0 & 576460752303423488L) != 0L)
            return mccStartNfaWithStates_0(3, 59, 11);
         return mccMoveStringLiteralDfa4_0(active0, 5765733422941077504L, active1, 0L);
      default :
         break;
   }
   return mccStartNfa_0(2, active0, active1);
}
private int mccMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return mccStartNfa_0(2, old0, old1); 
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch((int)curChar) {
      case 99:
         return mccMoveStringLiteralDfa5_0(active0, 4611686018427387904L);
      case 100:
         if ((active0 & 144115188075855872L) != 0L)
            return mccStartNfaWithStates_0(4, 57, 11);
         break;
      case 101:
         if ((active0 & 1125899906842624L) != 0L)
            return mccStartNfaWithStates_0(4, 50, 11);
         break;
      case 108:
         return mccMoveStringLiteralDfa5_0(active0, -9223372036854775808L);
      case 115:
         if ((active0 & 1152921504606846976L) != 0L)
            return mccStartNfaWithStates_0(4, 60, 11);
         break;
      case 116:
         if ((active0 & 288230376151711744L) != 0L)
            return mccStartNfaWithStates_0(4, 58, 11);
         return mccMoveStringLiteralDfa5_0(active0, 72057594037927936L);
      default :
         break;
   }
   return mccStartNfa_0(3, active0, 0L);
}
private int mccMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return mccStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch((int)curChar) {
      case 97:
         return mccMoveStringLiteralDfa6_0(active0, 4611686018427387904L);
      case 101:
         return mccMoveStringLiteralDfa6_0(active0, 72057594037927936L);
      case 108:
         return mccMoveStringLiteralDfa6_0(active0, -9223372036854775808L);
      default :
         break;
   }
   return mccStartNfa_0(4, active0, 0L);
}
private int mccMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return mccStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch((int)curChar) {
      case 100:
         if ((active0 & 72057594037927936L) != 0L)
            return mccStartNfaWithStates_0(6, 56, 11);
         break;
      case 101:
         return mccMoveStringLiteralDfa7_0(active0, -9223372036854775808L);
      case 110:
         if ((active0 & 4611686018427387904L) != 0L)
            return mccStartNfaWithStates_0(6, 62, 11);
         break;
      default :
         break;
   }
   return mccStartNfa_0(5, active0, 0L);
}
private int mccMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return mccStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) {
      mccStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch((int)curChar) {
      case 108:
         if ((active0 & -9223372036854775808L) != 0L)
            return mccStartNfaWithStates_0(7, 63, 11);
         break;
      default :
         break;
   }
   return mccStartNfa_0(6, active0, 0L);
}
private void mccCheckNAdd(int state)
{
   if (mccrounds[state] != mccround)
   {
      mccstateSet[mccnewStateCnt++] = state;
      mccrounds[state] = mccround;
   }
}
private void mccAddStates(int start, int end)
{
   do {
      mccstateSet[mccnewStateCnt++] = mccnextStates[start];
   } while (start++ != end);
}
private void mccCheckNAddTwoStates(int state1, int state2)
{
   mccCheckNAdd(state1);
   mccCheckNAdd(state2);
}
private void mccCheckNAddStates(int start, int end)
{
   do {
      mccCheckNAdd(mccnextStates[start]);
   } while (start++ != end);
}
private void mccCheckNAddStates(int start)
{
   mccCheckNAdd(mccnextStates[start]);
   mccCheckNAdd(mccnextStates[start + 1]);
}
static readonly long[] mccbitVec0 = {
   0L, 0L, -1L, -1L
};
private int mccMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   mccnewStateCnt = 60;
   int i = 1;
   mccstateSet[0] = startState;
   int j, kind = Int32.MaxValue;
   for (;;)
   {
      if (++mccround == Int32.MaxValue)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(mccstateSet[--i])
            {
               case 60:
                  if ((287948901175001088 & l) != 0L)
                  {
                     if (kind > 66)
                        kind = 66;
                     mccCheckNAddStates(0, 2);
                  }
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddStates(3, 5);
                  break;
               case 0:
                  if ((287948901175001088 & l) != 0L)
                  {
                     if (kind > 68)
                        kind = 68;
                     mccCheckNAddStates(6, 22);
                  }
                  else if (curChar == 46)
                     mccCheckNAddTwoStates(40, 44);
                  else if (curChar == 39)
                     mccCheckNAddStates(23, 25);
                  else if (curChar == 34)
                     mccCheckNAddStates(26, 28);
                  if (curChar == 48)
                     mccAddStates(29, 32);
                  break;
               case 1:
                  if (curChar == 34)
                     mccCheckNAddStates(26, 28);
                  break;
               case 3:
                  if ((-17179878401 & l) != 0L)
                     mccCheckNAddStates(26, 28);
                  break;
               case 4:
                  if (curChar == 34 && kind > 76)
                     kind = 76;
                  break;
               case 5:
               case 6:
                  if (curChar == 39)
                     mccCheckNAddStates(23, 25);
                  break;
               case 8:
                  if ((-549755823105 & l) != 0L)
                     mccCheckNAddStates(23, 25);
                  break;
               case 9:
                  if (curChar == 39 && kind > 77)
                     kind = 77;
                  break;
               case 11:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  mccstateSet[mccnewStateCnt++] = 11;
                  break;
               case 12:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  mccCheckNAddStates(6, 22);
                  break;
               case 13:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddStates(33, 36);
                  break;
               case 14:
                  if (curChar == 46)
                     mccCheckNAdd(15);
                  break;
               case 15:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddStates(37, 39);
                  break;
               case 17:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAdd(18);
                  break;
               case 18:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(18, 19);
                  break;
               case 20:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(20, 21);
                  break;
               case 21:
                  if (curChar == 46)
                     mccCheckNAdd(22);
                  break;
               case 22:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  mccCheckNAddStates(40, 42);
                  break;
               case 24:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAdd(25);
                  break;
               case 25:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  mccCheckNAddTwoStates(25, 26);
                  break;
               case 27:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(27, 28);
                  break;
               case 29:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAdd(30);
                  break;
               case 30:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  mccCheckNAddTwoStates(30, 26);
                  break;
               case 31:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(31, 26);
                  break;
               case 32:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  mccCheckNAdd(32);
                  break;
               case 33:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(33, 34);
                  break;
               case 35:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(35, 36);
                  break;
               case 37:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(37, 38);
                  break;
               case 39:
                  if (curChar == 46)
                     mccCheckNAddTwoStates(40, 44);
                  break;
               case 40:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddStates(3, 5);
                  break;
               case 42:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAdd(43);
                  break;
               case 43:
                  if ((287948901175001088 & l) != 0L)
                     mccCheckNAddTwoStates(43, 19);
                  break;
               case 44:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  mccCheckNAddStates(0, 2);
                  break;
               case 46:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAdd(47);
                  break;
               case 47:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  mccCheckNAddTwoStates(47, 26);
                  break;
               case 48:
                  if (curChar == 48)
                     mccAddStates(29, 32);
                  break;
               case 50:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  mccstateSet[mccnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((287948901175001088 & l) != 0L)
                     mccAddStates(43, 44);
                  break;
               case 55:
                  if ((287948901175001088 & l) != 0L)
                     mccAddStates(45, 46);
                  break;
               case 58:
                  if ((287948901175001088 & l) != 0L)
                     mccAddStates(47, 48);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 63);
         do
         {
            switch(mccstateSet[--i])
            {
               case 0:
               case 11:
                  if ((576460745995190270 & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  mccCheckNAdd(11);
                  break;
               case 2:
                  if (curChar == 92)
                     mccstateSet[mccnewStateCnt++] = 1;
                  break;
               case 3:
                  mccAddStates(26, 28);
                  break;
               case 7:
                  if (curChar == 92)
                     mccstateSet[mccnewStateCnt++] = 6;
                  break;
               case 8:
                  mccAddStates(23, 25);
                  break;
               case 16:
                  if ((137438953504 & l) != 0L)
                     mccAddStates(49, 50);
                  break;
               case 19:
                  if ((274877907008 & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               case 23:
                  if ((137438953504 & l) != 0L)
                     mccAddStates(51, 52);
                  break;
               case 26:
                  if ((68719476752 & l) != 0L && kind > 66)
                     kind = 66;
                  break;
               case 28:
                  if ((137438953504 & l) != 0L)
                     mccAddStates(53, 54);
                  break;
               case 34:
                  if ((144115188109410304 & l) != 0L && kind > 69)
                     kind = 69;
                  break;
               case 36:
                  if ((2251799814209536 & l) != 0L && kind > 70)
                     kind = 70;
                  break;
               case 38:
                  if ((17592186048512 & l) != 0L && kind > 71)
                     kind = 71;
                  break;
               case 41:
                  if ((137438953504 & l) != 0L)
                     mccAddStates(55, 56);
                  break;
               case 45:
                  if ((137438953504 & l) != 0L)
                     mccAddStates(57, 58);
                  break;
               case 49:
                  if (curChar == 120)
                     mccCheckNAdd(50);
                  break;
               case 50:
                  if ((541165879422 & l) == 0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  mccCheckNAdd(50);
                  break;
               case 51:
                  if (curChar == 120)
                     mccCheckNAdd(52);
                  break;
               case 52:
                  if ((541165879422 & l) != 0L)
                     mccCheckNAddTwoStates(52, 53);
                  break;
               case 53:
                  if ((144115188109410304 & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 54:
                  if (curChar == 120)
                     mccCheckNAdd(55);
                  break;
               case 55:
                  if ((541165879422 & l) != 0L)
                     mccCheckNAddTwoStates(55, 56);
                  break;
               case 56:
                  if ((2251799814209536 & l) != 0L && kind > 74)
                     kind = 74;
                  break;
               case 57:
                  if (curChar == 120)
                     mccCheckNAdd(58);
                  break;
               case 58:
                  if ((541165879422 & l) != 0L)
                     mccCheckNAddTwoStates(58, 59);
                  break;
               case 59:
                  if ((17592186048512 & l) != 0L && kind > 75)
                     kind = 75;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 63);
         do
         {
            switch(mccstateSet[--i])
            {
               case 3:
                  if ((mccbitVec0[i2] & l2) != 0L)
                     mccAddStates(26, 28);
                  break;
               case 8:
                  if ((mccbitVec0[i2] & l2) != 0L)
                     mccAddStates(23, 25);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != Int32.MaxValue)
      {
         mccmatchedKind = kind;
         mccmatchedPos = curPos;
         kind = Int32.MaxValue;
      }
      ++curPos;
      if ((i = mccnewStateCnt) == (startsAt = 60 - (mccnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.ReadChar(); }
      catch(System.IO.IOException) { return curPos; }
   }
}
static readonly int[] mccnextStates = {
   44, 45, 26, 40, 41, 19, 13, 14, 16, 19, 20, 21, 27, 28, 31, 26, 
   32, 33, 34, 35, 36, 37, 38, 7, 8, 9, 2, 3, 4, 49, 51, 54, 
   57, 13, 14, 16, 19, 15, 16, 19, 22, 23, 26, 52, 53, 55, 56, 58, 
   59, 17, 18, 24, 25, 29, 30, 42, 43, 46, 47, 
};
public static readonly string[] mccstrLiteralImages = {
"", null, null, null, null, "=", "=>", "|>", "&>", ",", "$", "&&", "&", "||", 
"|", "^", "==", "!=", "<=", ">=", "~~", "~", "*", "+", "/", "\\", "!", "(", ")", 
"[", "]", "<", ">", "<<", ">>", "{", "}", ":", "::", "%", "?", "@", "->", ".", 
"<;", ";>", ";", ";;", "def", "true", "false", "new", "null", "for", "if", "in", 
"visited", "yield", "count", "this", "class", "scan", "tryscan", "parallel", "lock", null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, ">>>", 
"-", null, };
public static readonly string[] lexStateNames = {
   "DEFAULT", 
};
static readonly long[] mcctoToken = {
   -31, 262135, 
};
static readonly long[] mcctoSkip = {
   30, 0, 
};
protected SimpleCharStream input_stream;
private readonly int[] mccrounds = new int[60];
private readonly int[] mccstateSet = new int[120];
System.Text.StringBuilder image;
int mccimageLen;
int lengthOfMatch;
protected char curChar;
public SequenceParserTokenManager(SimpleCharStream stream) {
   if (SimpleCharStream.staticFlag)
      throw new System.SystemException("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public SequenceParserTokenManager(SimpleCharStream stream, int lexState) :
   this(stream) {
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream) {
   mccmatchedPos = mccnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   mccround = -2147483647;
   for (i = 60; i-- > 0;)
      mccrounds[i] = Int32.MinValue;
}
public void ReInit(SimpleCharStream stream, int lexState) {
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState) {
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.InvalidLexicalState);
   else
      curLexState = lexState;
}

protected Token mccFillToken()
{
   Token t = Token.NewToken(mccmatchedKind);
   t.kind = mccmatchedKind;
   string im = mccstrLiteralImages[mccmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.BeginLine;
   t.beginColumn = input_stream.BeginColumn;
   t.endLine = input_stream.EndLine;
   t.endColumn = input_stream.EndColumn;
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int mccnewStateCnt;
int mccround;
int mccmatchedPos;
int mccmatchedKind;

public Token GetNextToken() {
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

for (;;) {
   try {
      curChar = input_stream.BeginToken();
   } catch(System.IO.IOException) {
      mccmatchedKind = 0;
      matchedToken = mccFillToken();
      return matchedToken;
   }
   image = null;
   mccimageLen = 0;

   try { input_stream.Backup(0);
      while (curChar <= ' ' && (4294977024L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   } catch (System.IO.IOException) { goto EOFLoop; }
   mccmatchedKind = Int32.MaxValue;
   mccmatchedPos = 0;
   curPos = mccMoveStringLiteralDfa0_0();
   if (mccmatchedPos == 0 && mccmatchedKind > 81)
   {
      mccmatchedKind = 81;
   }
   if (mccmatchedKind != Int32.MaxValue) {
      if (mccmatchedPos + 1 < curPos)
         input_stream.Backup(curPos - mccmatchedPos - 1);
      if ((mcctoToken[mccmatchedKind >> 6] & (1L << (mccmatchedKind & 63))) != 0L) {
         matchedToken = mccFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         goto EOFLoop;
      }
   }
   int error_line = input_stream.EndLine;
   int error_column = input_stream.EndColumn;
   string error_after = null;
   bool EOFSeen = false;
   try { input_stream.ReadChar(); input_stream.Backup(1); }
   catch (System.IO.IOException) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      } else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.Backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LexicalError);
EOFLoop: ;
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(mccmatchedKind) {
      case 76 :
        if (image == null)
            image = new System.Text.StringBuilder(new String(input_stream.GetSuffix(mccimageLen + (lengthOfMatch = mccmatchedPos + 1))));
         else
            image.Append(new String(input_stream.GetSuffix(mccimageLen + (lengthOfMatch = mccmatchedPos + 1))));
          matchedToken.image = matchedToken.image.Substring(1, matchedToken.image.Length-2);
         break;
      case 77 :
        if (image == null)
            image = new System.Text.StringBuilder(new String(input_stream.GetSuffix(mccimageLen + (lengthOfMatch = mccmatchedPos + 1))));
         else
            image.Append(new String(input_stream.GetSuffix(mccimageLen + (lengthOfMatch = mccmatchedPos + 1))));
          matchedToken.image = matchedToken.image.Substring(1, matchedToken.image.Length-2);
         break;
      default : 
         break;
   }
}
}
}
